// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'D:/RND/inventory-umi/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import DashboardOutlined from 'D:/RND/inventory-umi/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import FormOutlined from 'D:/RND/inventory-umi/node_modules/@ant-design/icons/es/icons/FormOutlined';
import TableOutlined from 'D:/RND/inventory-umi/node_modules/@ant-design/icons/es/icons/TableOutlined';
import CheckCircleOutlined from 'D:/RND/inventory-umi/node_modules/@ant-design/icons/es/icons/CheckCircleOutlined';
import WarningOutlined from 'D:/RND/inventory-umi/node_modules/@ant-design/icons/es/icons/WarningOutlined';
import UserOutlined from 'D:/RND/inventory-umi/node_modules/@ant-design/icons/es/icons/UserOutlined';
import SettingOutlined from 'D:/RND/inventory-umi/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { SmileOutlined, DashboardOutlined, FormOutlined, TableOutlined, CheckCircleOutlined, WarningOutlined, UserOutlined, SettingOutlined };
