// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Volumes/Projects/Personal/ERP-HUB/inventory-umi/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import DashboardOutlined from '/Volumes/Projects/Personal/ERP-HUB/inventory-umi/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import FormOutlined from '/Volumes/Projects/Personal/ERP-HUB/inventory-umi/node_modules/@ant-design/icons/es/icons/FormOutlined';
import TableOutlined from '/Volumes/Projects/Personal/ERP-HUB/inventory-umi/node_modules/@ant-design/icons/es/icons/TableOutlined';
import CheckCircleOutlined from '/Volumes/Projects/Personal/ERP-HUB/inventory-umi/node_modules/@ant-design/icons/es/icons/CheckCircleOutlined';
import WarningOutlined from '/Volumes/Projects/Personal/ERP-HUB/inventory-umi/node_modules/@ant-design/icons/es/icons/WarningOutlined';
import UserOutlined from '/Volumes/Projects/Personal/ERP-HUB/inventory-umi/node_modules/@ant-design/icons/es/icons/UserOutlined';
import SettingOutlined from '/Volumes/Projects/Personal/ERP-HUB/inventory-umi/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { SmileOutlined, DashboardOutlined, FormOutlined, TableOutlined, CheckCircleOutlined, WarningOutlined, UserOutlined, SettingOutlined };
